### ISSUE TITLE
增加了history的消息

### ISSUE THREAD

**Issue by ronalfei** [lin-xi/xpro#11]
在连接建立好后, 会收到类型为history的消息:结构如下:
{
    "from":"<0.910.0>",
    "xnest":"14009e12d791e664fc0175aecb31d833",
    "type":"history",
     "payload":
                    [
                     {"from":"<0.870.0>","payload":"å¯, åè½é½å¨","send_time":"2015-06-24"},
                     {"from":"<0.876.0>","payload":"ç°å¨è¿ä¸ªçªå£å¾æ£","send_time":"2015-06-24"},
                     {"from":"<0.876.0>","payload":"ä¸ç¥å","send_time":"2015-06-24"},
                     {"from":"<0.870.0>","payload":"è¿æä¸ä¸ªç½ä¼¯æ¯ç¹æ¯è°?","send_time":"2015-06-24"},
                     {"from":"<0.870.0>","payload":"æåå­æ¹æåä¸ç®­å¤´å°±å¥½.","send_time":"2015-06-24"},
                     {"from":"<0.870.0>","payload":"æ²¡æç¡®å®æé®, ä¼¼ä¹æç¹æª.","send_time":"2015-06-24"},
                  ],
    "send_time":"2015-6-24 11:5:16"}

payload里面就是一个消息数组.
某些情况下,payload里的from可能找不到对应的用户存在(已经离开). 此时随机一个昵称就好.

**Comment by lin-xi** [comment]
done
