### ISSUE TITLE
加载js文件的时候提供一个配置聊天空间的地方

### ISSUE THREAD

**Issue by ronalfei** [lin-xi/xpro#2]
可以参看这里
http://note.youdao.com/share/?id=a613b4f4e10ff7c83bb546183fe9c550&type=note

**Comment by lin-xi** [comment]
已改成下面的形式

<script src="api/xmeet.api.js?room=testroom"></script>

**Comment by lin-xi** [comment]
src="api/xmeet.api.js?roomId=demo&roomName=交流群"

**Comment by ronalfei** [comment]
good
