### ISSUE TITLE
ie进来之后, 用户昵称会是乱码.

### ISSUE THREAD

**Issue by ronalfei** [lin-xi/xpro#20]
这个具体看一下是什么问题, 我觉得应该很好解决才对.

**Comment by ronalfei** [comment]
![image](https://cloud.githubusercontent.com/assets/792840/8551072/01c78e04-2507-11e5-81c9-686d145518e7.png)

**Comment by ronalfei** [comment]
居然有那么多ie用户, 还是得看看这个问题.
这些乱码用户如果发消息, 显示出来的昵称又不是乱码...

**Comment by lin-xi** [comment]
应该是socket消息中返回的就是乱码

**Comment by ronalfei** [comment]
针对ie做了urlencode, 应该解决了问题. 关闭了
