### ISSUE TITLE
表情发送问题

### ISSUE THREAD

**Issue by ronalfei** [lin-xi/xpro#21]
现在表情的发送是利用发送html的原理进行的. 这样会导致传输大量无用的数据, 占用带宽, 能否简化发送的数据,比如:发送一个笑脸表情是   ＃12: 来表示, 头尾分别是井号和冒号,中间数字表示表情.
接收到这个字符串之后, 在渲染的时候把他替换成表情图片.这样能减少一下数据流量的产生.

**Comment by MatumbaMan** [comment]
这样我就方便了

**Comment by lin-xi** [comment]
可以

**Comment by lin-xi** [comment]
done
