### ISSUE TITLE
添加个安全性开关

### ISSUE THREAD

**Issue by ronalfei** [lin-xi/xpro#24]
能否在meet.api.js的参数中添加一个security的参数,=1或者0.
等于1就启用wss的协议去连接, 
等于0就默认用ws的协议去连接.
提高一下数据在网络上传输的安全性.
wss目前服务器已经是开放的.

**Comment by lin-xi** [comment]
done

**Comment by ronalfei** [comment]
好，我先做个备注，当没有购买证书时，会引起浏览器连接不上服务器！

发自我的 iPhone
