### ISSUE TITLE
点击设置, 人头图标时,下拉速度感觉有点慢.

### ISSUE THREAD

**Issue by ronalfei** [lin-xi/xpro#3]
能否提高一点速度

**Comment by ronalfei** [comment]
还发现另外一个问题, 聊天条数多了以后, 下拉框就看不见了.

**Comment by ronalfei** [comment]
聊天条数多了以后, 发消息的特效有点点问题.

**Comment by lin-xi** [comment]
速度 由 0.6 -> 0.4

`还发现另外一个问题, 聊天条数多了以后, 下拉框就看不见了.`
done

`聊天条数多了以后, 发消息的特效有点点问题`
还好
