### ISSUE TITLE
新增加了改变昵称的功能

### ISSUE THREAD

**Issue by ronalfei** [lin-xi/xpro#6]
通过发送    @changename:新昵称     来改变当前用户的昵称.
发送出来后, 服务端会修改聊天室成员的昵称名字, 同时会像所有用户广播一个changename的消息.

js端可能需要做如下事情:
一, 当自己改名时:
1. 发送@changename:xxxx消息, 
2. 修改当前用户的cookie中的昵称名字,
3. 收到服务器广播自己的改名消息, 但无需做处理.

二. 收到别人改名的消息
1. 修改存在在js中的全局昵称变量. 
2. 可以以另外一种消息模板把这条消息显示出来.

**Comment by ronalfei** [comment]
第一次连接服务器后, 服务器会把昵称中在cookie里, 下次在连接的时候就直接用cookie里的昵称即可, 不用在重新带一个过来.

**Comment by lin-xi** [comment]
done
