### ISSUE TITLE
加载js的时候, 不添加roomid和name的参数应该有默认值.

### ISSUE THREAD

**Issue by ronalfei** [lin-xi/xpro#9]
roomid的默认值为域名+url来计算(url不带参数)
目的是为了直接加载<script src="v2/api/xmeet.api.js"><\/script>后, 每个页面(url+域名相同)就是一个独立的聊天空间. 现在的情况是:如果不带参数, 每次进入都是不同聊天空间.
roomname的参数我想默认为空就好了..
roomid和roomname, 我想和后面统一起来, room有点土.
roomid ==> xnest
roomname ==> xnest_name
都小写, 用_分割吧.

**Comment by ronalfei** [comment]
这个东西改完, 就可以用这个v2版本了.辛苦辛苦.

**Comment by lin-xi** [comment]
fixed
